// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddTorrent(arg1:string):Promise<app.Torrent>;

export function GetSettings():Promise<app.Settings>;

export function GetTorrentFiles(arg1:string):Promise<Array<app.TorrentFile>>;

export function GetTorrentStats(arg1:string):Promise<app.TorrentStats>;

export function GetTorrents():Promise<Array<app.Torrent>>;

export function PlayTorrentFile(arg1:string,arg2:number):Promise<void>;

export function RemoveTorrent(arg1:string):Promise<void>;

export function SetSettings(arg1:app.Settings):Promise<void>;
