// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {http} from '../models';

export function AddTorrent(arg1:string):Promise<app.Torrent>;

export function CheckAuthStatus():Promise<boolean>;

export function DeleteCookiesFile():Promise<void>;

export function GetCookiesPath():Promise<string>;

export function GetRegistrationCaptcha():Promise<app.CaptchaData>;

export function GetRutrackerMagnetLink(arg1:string):Promise<string>;

export function GetSettings():Promise<app.Settings>;

export function GetTorrentFiles(arg1:string):Promise<Array<app.TorrentFile>>;

export function GetTorrentStats(arg1:string):Promise<app.TorrentStats>;

export function GetTorrents():Promise<Array<app.Torrent>>;

export function LoadCookiesFromFile():Promise<Array<http.Cookie>>;

export function LoginToRuTracker(arg1:app.LoginData):Promise<void>;

export function LogoutFromRuTracker():Promise<void>;

export function PlayTorrentFile(arg1:string,arg2:number):Promise<void>;

export function RegisterOnRuTracker(arg1:app.RegistrationData):Promise<void>;

export function RemoveTorrent(arg1:string):Promise<void>;

export function SaveCookiesToFile(arg1:Array<http.Cookie>):Promise<void>;

export function SearchRuTracker(arg1:string):Promise<Array<app.RutrackerTorrent>>;

export function SetSettings(arg1:app.Settings):Promise<void>;
