// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTorrent(arg1) {
  return window['go']['app']['App']['AddTorrent'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetTorrentFiles(arg1) {
  return window['go']['app']['App']['GetTorrentFiles'](arg1);
}

export function GetTorrentStats(arg1) {
  return window['go']['app']['App']['GetTorrentStats'](arg1);
}

export function GetTorrents() {
  return window['go']['app']['App']['GetTorrents']();
}

export function PlayTorrentFile(arg1, arg2) {
  return window['go']['app']['App']['PlayTorrentFile'](arg1, arg2);
}

export function RemoveTorrent(arg1) {
  return window['go']['app']['App']['RemoveTorrent'](arg1);
}

export function SetSettings(arg1) {
  return window['go']['app']['App']['SetSettings'](arg1);
}
