// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTorrent(arg1:string):Promise<main.Torrent>;

export function GetSettings():Promise<main.Settings>;

export function GetTorrentFiles(arg1:string):Promise<Array<main.TorrentFile>>;

export function GetTorrentStats(arg1:string):Promise<main.TorrentStats>;

export function GetTorrents():Promise<Array<main.Torrent>>;

export function PlayTorrentFile(arg1:string,arg2:number):Promise<void>;

export function RemoveTorrent(arg1:string):Promise<void>;

export function SetSettings(arg1:main.Settings):Promise<void>;
